<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

!pip install sqlalchemy

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

!pip install ipython-sql
!pip install ipython-sql prettytable

In [1]:
!pip install pymysql
#weil ich mysql hat.

Requirement already satisfied: pymysql in C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.3)

!pip uninstall -y sqlalchemy

In [18]:
import pymysql
print(pymysql.__version__)

2.2.8

In [7]:
!pip show pymysql

Name: PyMySQL
Version: 1.2.3
Summary: Pure Python MySQL Driver
Home-page:
Author:
Author-email: Inada Naoki <songofacandy@gmail.com>, Yutaka Matsubara <yutaka.matsubara@gmail.com>
License-Expression: MIT
Location: C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages
Requires:
Required-by:

In [20]:
import sys
print(sys.executable)

C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [1]:
!where python

C:\Users\ugurp\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\ugurp\AppData\Local\Python\bin\python.exe

In [22]:
!pip --version

pip 26.2.1 from C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip (python 3.14)

In [23]:
import pymysql
print(pymysql.__file__)

C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pymysql\__init__.py

In [25]:
import sys
print(sys.executable)

import pymysql
print(pymysql.__version__)
print(pymysql.__file__)

!pip --version

C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\python.exe
2.2.8
C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pymysql\__init__.py
pip 26.2.1 from C:\Users\ugurp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip (python 3.14)

Du solltest dein Passwort niemals fest im Notebook hinterlegen, besonders wenn:

du das Notebook auf GitHub hochlädst
es mit anderen teilst
es Teil eines Coursera-Projekts wird

Stattdessen gibt es mehrere sichere Varianten.

**Für lokale Übungen: Passwort zur Laufzeit eingeben**
import getpass
import pymysql

password = getpass.getpass("MySQL-Passwort: ")

conn = pymysql.connect(
    host="localhost",
    user="root",
    password=password,
    database="SPACEXTBL"
)

print("✅ Verbindung erfolgreich")


Vorteil:

Passwort erscheint nicht im Notebook
Passwort wird nicht gespeichert
Variante mit Umgebungsvariable

**Einmal in PowerShell setzen:**

setx MYSQL_PASSWORD "dein_passwort"


Danach Windows Terminal/Jupyter neu starten.

Im Notebook:

import os
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root",
    password=os.getenv("MYSQL_PASSWORD"),
    database="SPACEXTBL"
)


Das ist die übliche professionelle Lösung.

**Datei außerhalb des Notebooks**

Datei config.py:

MYSQL_PASSWORD = "dein_passwort"


Notebook:

from config import MYSQL_PASSWORD


Wichtig: config.py nie auf GitHub hochladen.

Dazu eine .gitignore:

config.py


Für dein aktuelles IBM-Coursera-Projekt würde ich die einfachste und sichere Lösung nehmen:

import getpass

password = getpass.getpass("MySQL-Passwort: ")


Damit steht das Passwort nirgends im Notebook und du kannst trotzdem direkt auf deine SpaceX-Datenbank zugreifen.

In [29]:
import getpass
import pymysql

password = getpass.getpass("MySQL-Passwort: ")

conn = pymysql.connect(
    host="localhost",
    user="root",
    password=password,
    database="spacex_db"
)

print("✅ Verbindung erfolgreich")

MySQL-Passwort:  ········

✅ Verbindung erfolgreich

%load_ext sql

import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

!pip install -q pandas

%sql sqlite:///my_data1.db

In [31]:
import pandas as pd
df = pd.read_sql("SELECT * FROM spacex", conn)
df.head()

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\1257121406.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM spacex", conn)

,Date,Time_UTC,Booster_Version,Launch_Site,Payload,PAYLOAD_MASS_KG,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,0 days 18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute)\r
1,2010-12-08,0 days 15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)\r
2,2012-05-22,0 days 07:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525.0,LEO (ISS),NASA (COTS),Success,No attempt\r
3,2012-10-08,0 days 00:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt\r
4,2013-03-01,0 days 15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt\r

In [34]:
type(conn)

pymysql.connections.Connection

import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False, method="multi")

**Note:This below code is added to remove blank rows from table**

#DROP THE TABLE IF EXISTS

%sql DROP TABLE IF EXISTS SPACEXTABLE;

%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [33]:
query = """
SELECT DISTINCT Launch_Site
FROM spacex
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\814692742.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

    Launch_Site
0   CCAFS LC-40
1   VAFB SLC-4E
2    KSC LC-39A
3  CCAFS SLC-40


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [35]:
query = """
SELECT *
FROM spacex
WHERE Launch_Site LIKE 'CCA%'
LIMIT 5
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\575367334.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

,Date,Time_UTC,Booster_Version,Launch_Site,Payload,PAYLOAD_MASS_KG,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,0 days 18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute)\r
1,2010-12-08,0 days 15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)\r
2,2012-05-22,0 days 07:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525.0,LEO (ISS),NASA (COTS),Success,No attempt\r
3,2012-10-08,0 days 00:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt\r
4,2013-03-01,0 days 15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt\r

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [37]:
query = """
SELECT SUM(PAYLOAD_MASS_KG) AS total_payload_mass
FROM spacex
WHERE Customer = 'NASA (CRS)'
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\1218120175.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   total_payload_mass
0             45596.0

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [38]:
query = """
SELECT AVG(PAYLOAD_MASS_KG) AS average_payload_mass
FROM spacex
WHERE Booster_Version = 'F9 v1.1'
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\2729806298.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   average_payload_mass
0                2928.4

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [39]:
query = """
SELECT MIN(Date) AS first_successful_ground_pad_landing
FROM spacex
WHERE Landing_Outcome = 'Success (ground pad)'
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\2235056811.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

  first_successful_ground_pad_landing
0                                None

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [43]:
query = """
SELECT DISTINCT Booster_Version
FROM spacex
WHERE Landing_Outcome = 'Success (drone ship)\r'
  AND PAYLOAD_MASS_KG > 4000
  AND PAYLOAD_MASS_KG < 6000
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\2144327157.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

  Booster_Version
0     F9 FT B1022
1     F9 FT B1026
2  F9 FT  B1021.2
3  F9 FT  B1031.2

### Task 7




##### List the total number of successful and failure mission outcomes

In [44]:
query = """
SELECT Mission_Outcome,
       COUNT(*) AS total_count
FROM spacex
GROUP BY Mission_Outcome
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\1377835587.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                    Mission_Outcome  total_count
0                           Success           98
1               Failure (in flight)            1
2  Success (payload status unclear)            1
3                          Success             1

### Task 8



##### List all the booster_versions that have carried the maximum payload mass, using a subquery with a suitable aggregate function.

In [45]:
query = """
SELECT DISTINCT Booster_Version
FROM spacex
WHERE PAYLOAD_MASS_KG = (
    SELECT MAX(PAYLOAD_MASS_KG)
    FROM spacex
)
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\962012458.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

   Booster_Version
0    F9 B5 B1048.4
1    F9 B5 B1049.4
2    F9 B5 B1051.3
3    F9 B5 B1056.4
4    F9 B5 B1048.5
5    F9 B5 B1051.4
6    F9 B5 B1049.5
7   F9 B5 B1060.2
8   F9 B5 B1058.3
9    F9 B5 B1051.6
10   F9 B5 B1060.3
11  F9 B5 B1049.7

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [46]:
query = """
SELECT MONTHNAME(Date) AS Month,
       Landing_Outcome,
       Booster_Version,
       Launch_Site
FROM spacex
WHERE YEAR(Date) = 2015
  AND Landing_Outcome LIKE '%Failure%drone ship%';
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\3551816108.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

     Month         Landing_Outcome Booster_Version  Launch_Site
0  January  Failure (drone ship)\r   F9 v1.1 B1012  CCAFS LC-40
1    April  Failure (drone ship)\r   F9 v1.1 B1015  CCAFS LC-40

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [47]:
query = """
SELECT Landing_Outcome,
       COUNT(*) AS Count_Landing_Outcome
FROM spacex
WHERE Date BETWEEN '2010-06-04' AND '2017-03-20'
GROUP BY Landing_Outcome
ORDER BY Count_Landing_Outcome DESC;
"""

pd.read_sql(query, conn)

C:\Users\ugurp\AppData\Local\Temp\ipykernel_18120\2556901773.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

            Landing_Outcome  Count_Landing_Outcome
0              No attempt\r                     10
1    Failure (drone ship)\r                      5
2    Success (drone ship)\r                      5
3      Controlled (ocean)\r                      3
4    Success (ground pad)\r                      3
5     Failure (parachute)\r                      2
6    Uncontrolled (ocean)\r                      2
7  Precluded (drone ship)\r                      1

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

<!--
## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2024-07-10 | 1.1 |Anita Verma | Changed Version|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |
-->

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>

Die SQL-Magic-Befehle (%sql und %%sql) funktionieren nicht nur mit SQLite, sondern auch mit MySQL, MariaDB, PostgreSQL, SQL Server und vielen anderen Datenbanken, sofern ein passender Treiber installiert ist.

Für MySQL benötigst du typischerweise:

!pip install ipython-sql pymysql


Dann:

%load_ext sql


Verbindung herstellen:

%sql mysql+pymysql://root@localhost/SPACEXTBL


Oder sicherer ohne Passwort im Code:

import getpass

password = getpass.getpass("Passwort: ")

%sql mysql+pymysql://root:$password@localhost/SPACEXTBL


Danach kannst du SQL direkt schreiben:

%%sql

SELECT DISTINCT Launch_Site
FROM spacex;


oder

%%sql

SELECT COUNT(*)
FROM spacex;

Vorteil gegenüber pymysql

Statt:

query = """
SELECT DISTINCT Launch_Site
FROM spacex
"""

pd.read_sql(query, conn)


kannst du einfach schreiben:

%%sql

SELECT DISTINCT Launch_Site
FROM spacex;


Das ist besonders praktisch für den IBM Data Science Capstone, weil viele Kursbeispiele genau so aufgebaut sind.

Prüfen, ob SQL-Magic installiert ist
!pip show ipython-sql


Wenn nichts gefunden wird:

!pip install ipython-sql


Da du gerade die fehlerhaften ~alchemy- und ~upyterlab-Ordner gelöscht hast, besteht eine gute Chance, dass %load_ext sql jetzt problemlos funktioniert. Teste einfach:

%load_ext sql


Wenn eine Fehlermeldung erscheint, zeig sie mir. Wenn keine erscheint, können wir direkt deine MySQL-Datenbank mit SQL-Magic verbinden. 🚀